{"uuid": "79d2b013-6602-4863-ba5a-0c71a2f59afe", "children": ["3d8a3762-52d9-4e5e-9c92-3f02833c070d"], "befores": [{"name": "driver", "status": "passed", "start": 1740491197129, "stop": 1740491200589}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\Lenovo ThinkBook\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Lenovo ThinkBook\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Lenovo ThinkBook\\Desktop\\QA\\pytest\\conftest.py\", line 17, in driver\n    driver.quit()\n    ~~~~~~~~~~~^^\n  File \"C:\\Users\\Lenovo ThinkBook\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Lenovo ThinkBook\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\selenium\\webdriver\\common\\service.py\", line 157, in stop\n    self.send_remote_shutdown_command()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Lenovo ThinkBook\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\selenium\\webdriver\\common\\service.py\", line 137, in send_remote_shutdown_command\n    request.urlopen(f\"{self.service_url}/shutdown\")\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\\Lib\\urllib\\request.py\", line 186, in urlopen\n    _opener = opener = build_opener()\n                       ~~~~~~~~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\\Lib\\urllib\\request.py\", line 567, in build_opener\n    opener.add_handler(klass())\n                       ~~~~~^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\\Lib\\urllib\\request.py\", line 1361, in __init__\n    context = http.client._create_https_context(http_version)\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\\Lib\\http\\client.py\", line 809, in _create_https_context\n    context = ssl._create_default_https_context()\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\\Lib\\ssl.py\", line 722, in create_default_context\n    context.load_default_certs(purpose)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\\Lib\\ssl.py\", line 533, in load_default_certs\n    self._load_windows_store_certs(storename, purpose)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.752.0_x64__qbz5n2kfra8p0\\Lib\\ssl.py\", line 522, in _load_windows_store_certs\n    self.load_verify_locations(cadata=cert)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n"}, "start": 1740491200743, "stop": 1740491200881}], "start": 1740491197129, "stop": 1740491200881}